<?php

namespace EniBundle\Repository;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatRepository extends \Doctrine\ORM\EntityRepository
{
}
