<?php

namespace EniBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
    
    public function getInscription(){
        
        //on recupere l'entity manager
        //$em = $this->getDoctrine()->getManager();
        
        //requete DQL
        //$dql = 'SELECT i FROM EniBundle:Inscription i WHERE i.etat <> "terminé" ORDER BY i.dureeValidite ASC ';
        $dql = 'SELECT i FROM EniBundle:Inscription i ORDER BY i.dureeValidite ASC ';
        
        // creation de la query (c'est un peu le prepare du php classique)
        $query = $this->getEntityManager()->createQuery($dql);
        
        //on retourne l'execution de la query
        return $query->getResult();
    }
}
