<?php

namespace EniBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
    
    public function getInscription($id){

        //$dql = 'SELECT i FROM EniBundle:Inscription i, FROM EniBundle:User u WHERE i.etat <> "terminé" ORDER BY i.dureeValidite ASC ';
        $dql = 'SELECT i FROM EniBundle:Inscription i WHERE i.utilisateur ='.$id; 
        
        // creation de la query 
        $query = $this->getEntityManager()->createQuery($dql);
        
        //on retourne l'execution de la query
        return $query->getResult();
    }
}
