<?php

namespace EniBundle\Repository;

/**
 * MultipleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultipleRepository extends \Doctrine\ORM\EntityRepository
{
}
