<?php

namespace EniBundle\Repository;

/**
 * QestionTirageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QestionTirageRepository extends \Doctrine\ORM\EntityRepository
{
}
