<?php

namespace EniBundle\Repository;

/**
 * SectionTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionTestRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSection($id){
        
        $dql = 'SELECT s FROM EniBundle:SectionTest s WHERE s.test ='.$id;
        
        // creation de la query 
        $query = $this->getEntityManager()->createQuery($dql);
        
        //on retourne l'execution de la query
        return $query->getResult();
    }
    
}
