<?php

namespace EniBundle\Repository;

/**
 * StaffEniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffEniRepository extends \Doctrine\ORM\EntityRepository
{
}
