index_route:
    path: /index
    defaults: { _controller: EniBundle:Default:index }

home_route:
    path: /
    defaults: { _controller: EniBundle:Default:index }
    
accueilcandidat_route:
    path: /candidat
    defaults: { _controller: EniBundle:User:view }
    
accueilstaff_route:
    path: /staff
    defaults: { _controller: EniBundle:User:view }
    
confirmtest_route:
    path: /test
    defaults: { _controller: EniBundle:User:confirmTest }