index_route:
    path: /index
    defaults: { _controller: EniBundle:Default:index }

home_route:
    path: /
    defaults: { _controller: EniBundle:Default:index }
    
accueilcandidat_route:
    path: /candidat
    defaults: { _controller: EniBundle:User:view }
    
accueilstaff_route:
    path: /staff
    defaults: { _controller: EniBundle:User:view }
    
confirmtest_route:
    path: /test/{id}
    defaults: { _controller: EniBundle:User:confirmTest }
    
initTest_route:
    path: /tes/{id}/{numQuestion}
    defaults: { _controller: EniBundle:Test:initTest }

test_route:
    path: /tes/{id}/{numQuestion}
    defaults: { _controller: EniBundle:Test:passerTest }

admintheme_route:
    path:     /admintheme
    defaults: { _controller: EniBundle:Staff:themeview }
    
adminquestion_route:
    path:     /addquestion
    defaults: { _controller: EniBundle:Staff:addquestion }
